---
db_host: "YOUR_DATABASE_HOST"
db_name: "YOUR_DATABASE_NAME"
db_username: "YOUR_DATABASE_USER_USERNAME"
db_password: "YOUR_DATABASE_USER_PASSWORD"
db_root_user: "YOUR_DATABASE_ROOT_USER"
db_root_password: "YOUR_DATABASE_ROOT_PASSWORD"
passbolt_url: "YOUR_PASSBOLT_FULL_BASE_URL"

webserver_user: "YOUR_WEBSERVER_USER"
php_version: "YOUR_PHP_VERSION" # Debian12 = 8.2 / Ubuntu 24.04 = 8.3 / Debian 11 = 7.4 / AlmaLinux 9 = 8.1
passbolt_edition: "PASSBOLT_EDITION"  # Options: ce || pro
passbolt_repositories:
  ce: "https://download.passbolt.com/ce/installer/passbolt-repo-setup.ce.sh"
  pro: "https://download.passbolt.com/pro/installer/passbolt-repo-setup.pro.sh"

ssl_subj: "/C=YOUR_COUNTRY/ST=YOUR_STATE/L=YOUR_CITY/O=YOUR_ORGANIZATION/OU=YOUR_ORG_UNIT/CN=YOUR_COMMON_NAME/"
ssl_subjectAltName: "DNS:YOUR_DOMAIN"

