---
- name: Gather facts about the host
  ansible.builtin.setup:

- name: Configure Nginx (Debian/Ubuntu)
  template:
    src: templates/deb/nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  when: ansible_facts['os_family'] == "Debian"

- name: Configure Nginx (RedHat/AlmaLinux)
  template:
    src: templates/rpm/nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  when: ansible_facts['os_family'] == "RedHat"

- name: Configure Passbolt Nginx site (Debian/Ubuntu)
  template:
    src: templates/deb/nginx/passbolt.conf.j2
    dest: /etc/nginx/sites-available/passbolt.conf
    owner: root
    group: root
    mode: '0644'
  when: ansible_facts['os_family'] == "Debian"

- name: Configure Passbolt Nginx site (RedHat/AlmaLinux)
  template:
    src: templates/rpm/nginx/passbolt.conf.j2
    dest: /etc/nginx/conf.d/passbolt.conf
    owner: root
    group: root
    mode: '0644'
  when: ansible_facts['os_family'] == "RedHat"

- name: Configure Passbolt SSL settings (Debian/Ubuntu)
  template:
    src: templates/deb/nginx/nginx-ssl.conf.j2
    dest: /etc/passbolt/nginx-ssl.conf
    owner: root
    group: root
    mode: '0644'
  when: ansible_facts['os_family'] == "Debian"

- name: Configure Passbolt SSL settings (RedHat/AlmaLinux)
  template:
    src: templates/rpm/nginx/nginx-ssl.conf.j2
    dest: /etc/nginx/conf.d/passbolt_ssl.conf
    owner: root
    group: root
    mode: '0644'
  when: ansible_facts['os_family'] == "RedHat"

- name: Configure Passbolt SSL settings (RedHat/AlmaLinux)
  template:
    src: templates/rpm/nginx/php-fpm.conf.j2
    dest: /etc/nginx/conf.d/php-fpm.conf
    owner: root
    group: root
    mode: '0644'
  when: ansible_facts['os_family'] == "RedHat"

- name: Enable Passbolt Nginx site (Debian/Ubuntu)
  file:
    src: /etc/nginx/sites-available/passbolt.conf
    dest: /etc/nginx/sites-enabled/passbolt.conf
    state: link
  when: ansible_facts['os_family'] == "Debian"

- name: Disable default Nginx site (Debian/Ubuntu)
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  when: ansible_facts['os_family'] == "Debian"

- name: Test Nginx configuration
  command: nginx -t
  notify:
    - Reload Nginx

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
    enabled: true
