---
- name: Configure Nginx
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'

- name: Configure Passbolt Nginx site
  template:
    src: templates/passbolt.conf.j2
    dest: /etc/nginx/sites-available/passbolt.conf
    owner: root
    group: root
    mode: '0644'

- name: Configure Passbolt SSL settings
  template:
    src: templates/nginx-ssl.conf.j2
    dest: /etc/passbolt/nginx-ssl.conf
    owner: root
    group: root
    mode: '0644'

- name: Check if Passbolt Nginx site exists
  stat:
    path: /etc/nginx/sites-available/passbolt.conf
  register: passbolt_site

- name: Debug Passbolt Nginx site existence
  debug:
    var: passbolt_site

- name: Enable Passbolt Nginx site
  file:
    src: /etc/nginx/sites-available/passbolt.conf
    dest: /etc/nginx/sites-enabled/passbolt.conf
    state: link
  when: passbolt_site.stat.exists

- name: Disable default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Test Nginx configuration
  command: nginx -t
  notify:
    - Reload Nginx

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
    enabled: true
